INSERT INTO blogful_articles (
    title, date_published, content
)
    VALUES 
    ('HAIR BENEFITS OF CHAMPAGNE: FACT OR FICTION?', now() - '21 days'::INTERVAL, 'I had some people over for a dinner party a few weeks and there was a nearly full bottle of Veuve left over.'),
    ('CAN EMSCULPT HELP YOU LOSE WEIGHT WITHOUT THE EFFORT?', now() - '47 days'::INTERVAL, 'If you follow influencers on social media you might be familiar with Emsculpt. It''s an FDA-approved, non-invasive, electromagnetic procedure that claims to eliminate fat cells and tighten muscles in your abs and butt.'),
    ('MUSHROOMS IN SKINCARE ARE HERE TO STAY (AND THAT’S A GOOD THING!)', now() - '1 days'::INTERVAL, 'There are so many gimmicks in skincare these days (please stop spam''ing me with CBD cream advertisements and press releases!).'),
    ('MAKE 2020 THE YEAR YOU GO CLEAN', now() - '2 days'::INTERVAL, 'If you live in California you''ve all but certainly seen warning labels on a product - as mandated by Prop 65 - letting you know that the product you''re about to use has chemicals that have been linked to cancer and/or reproductive issues.'),
    ('IS IT WORTH INVESTING IN A BEAUTY FRIDGE?', now() - '3 days'::INTERVAL, 'Right now the whole bottom area of my fridge is filled with beauty products. My husband doesn''t mind but he does, every so often, ask why I need so many products I never use.'),    
    ('HOLIDAY HAIR INSPO FROM CELEBRITY STYLIST MIA SANTIAGO', now() - '4 days'::INTERVAL, 'Mia Santiago, who started out at Sally Hershberger and regularly works with celebrities like Mariska Hargitay, Jesse Tyler Ferguson, and Kevin Bacon and editorials for the like of Vogue and Allure stopped by to share some of her go-to hair looks and tips for this holiday season.'),    
    ('HOLIDAY BEAUTY TIPS FROM CELEBRITY BEAUTY EXPERT GEOFFREY RODRIGUEZ', now() - '5 days'::INTERVAL, 'Geoffrey Rodriguez has worked on editorials for Vogue, Teen Vogue, W, Glamour, Marie Claire, and Harper''s Bazaar not to mention that he''s been in the industry for over two decades. Needless to say he knows a thing or two about helping women look their best.'),    
    ('EVERYTHING YOU NEED TO KNOW TO TREAT AND PREVENT DRY NAILS', now() - '5 days'::INTERVAL, NULL),    
    ('A COSMETIC BAG FOR EVERY OCCASION', now() - '7 days'::INTERVAL, 'If you''re anything like me, you like options (my husband always jokes that it won''t be long before the only room for his stuff will be under the bed...). But when it comes to beauty bags, options can also mean that your things are better organized.'),  
    ('CAN TRUFFLE ACTUALLY HAVE BENEFITS FOR YOUR HAIR?', now() - '7 days'::INTERVAL, 'I went to a launch event a few weeks ago for the Black Truffle Hair Care Collection from Moroccan Gold. It was at the gorgeous new John Barrett Salon in NYC (the one that used to be at Bergdorf Goodman).'),    
    ('THE BEST 2019 BLACK FRIDAY AND CYBER MONDAY SHOPPING DEALS SO FAR', now() - '8 days'::INTERVAL, 'Why wait till Black Friday? There are plenty of deals to jump on right now (that don''t require decision-making while nursing a food coma...). I, for one, won''t be doing any shopping this year in-store as pretty much every retailer is offering amazing deals online - many of which have already started.'),    
    ('THE EXPERTS AGREE: OTC CELLULITE PRODUCTS DON’T WORK! (AND LASERS ARE OVER-RATED)', now() - '10 days'::INTERVAL, NULL),    
    ('WHY WELLNESS EXPERTS ARE BUZZING ABOUT COCONUT AMINOS', now() - '12 days'::INTERVAL, 'If you''re a regular shopper at Trader Joe''s or Whole Foods you''ve probably seen a stack of Coconut Aminos bottles next to the selection of Soy Sauce.'),    
    ('ALL YOUR QUESTIONS ABOUT EYE CARE ANSWERED', now() - '12 days'::INTERVAL, 'Turns out I''ve been applying my eye cream all wrong! Dangerously close to my eye and needlessly on my eyelids. And I have a feeling I''m not the only one. '),    
    ('HOW TO KEEP YOUR SKIN HEALTHY, DECADE BY DECADE', now() - '18 days'::INTERVAL, 'Wrinkles and acne aren''t fun for anyone, but with the onslaught of new lasers, peels, facials, and treatment beauty products it can be hard to know what we actually need and when, which is why I turned to Dr. Lamees Hamdan, founder of Shiffa.'),    
    ('EVERYTHING YOU NEED TO KNOW ABOUT BUZZY BEAUTY INGREDIENT CENTELLA', now() - '20 days'::INTERVAL, 'If you''re a Sephora regular you''ve probably noticed a spike in products touting that they''re formulated with centella. But what in the heck exactly is this new buzzy ingredient and should you buy into the hype?'),      
    ('SKINCARE ACIDS EXPLAINED', now() - '22 days'::INTERVAL, 'Acids are game-changers. They''re the quickest way to get glowing skin, in my experience, and I''ve found them to key to preventing breakouts (along with using only oil-free products). But what are the major ones and what are the differences?'),    
    ('WHICH OIL ARE SAFE – AND WHICH ARE DANGEROUS – FOR ACNE-PRONE SKIN', now() - '28 days'::INTERVAL, NULL),    
    ('THESE PRODUCTS WILL HELP PRESERVE YOUR HAIR COLOR', now() - '26 days'::INTERVAL, NULL),    
    ('THE BEST AIR-DRY HAIR PRODUCTS FOR WHEN YOU’RE TOO LAZY TO HEAT STYLE', now() - '26 days'::INTERVAL, 'I love getting my hair done because it''s the best excuse to quiz the stylist about what hair products really actually are worth buying. I try a lot, but the top stylists really try a lot.')
    ;